name: todo_list
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  synchronized: ^3.0.1
  google_fonts: ^6.1.0
  flutter_signin_button: ^2.0.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  validatorless: ^1.2.3
  flutter_overlay_loader: ^2.0.0
  google_sign_in: ^6.1.6
  date_picker_timeline: ^1.2.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: TodoListIcons
      fonts:
        - asset: assets/fonts/TodoListIcons.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
